[phases.setup]
nixPkgs = ["python3", "postgresql_16.dev", "poppler_utils", "gcc"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && pip install --upgrade pip --no-cache-dir",
  ". /opt/venv/bin/activate && pip install --no-cache-dir --no-warn-script-location -r requirements.txt"
]

[start]
cmd = "python start_processor.py"

