[phases.setup]
nixPkgs = ["python3", "postgresql_16.dev", "poppler_utils", "gcc"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  "/opt/venv/bin/python -m pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "/opt/venv/bin/python start_processor.py"

